name: Publish Plover

permissions:
  actions: read
  contents: read
  checks: read
  packages: write
  statuses: write

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ruby/setup-ruby@v1.226.0
        with: 
          ruby-version: "3.4.2"
          bundler-cache: true

      - name: Set RELEASE_TAG
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: ruby .github/workflows/publish.rb
        env:
          PLOVER_FLAG_GEM_VERSION: ${{ env.RELEASE_TAG }}
          PLOVER_FLAG_RUBYGEMS_RELEASE_TOKEN: ${{ secrets.RUBYGEMS_RELEASE_TOKEN }}
          PLOVER_FLAG_GITHUB_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}